#ifndef TOKEN_TOKEN_TYPES_COMMENT_H
#define TOKEN_TOKEN_TYPES_COMMENT_H

#ifndef TOK_CLASS_COMMENT_TYPES_NUM
#define TOK_CLASS_COMMENT_TYPES_NUM 2
#define TOK_CLASS_COMMENT_SINGLE_TYPE 0
#define TOK_CLASS_COMMENT_SINGLE_OPENER "//"
#define TOK_CLASS_COMMENT_SINGLE_DEBUG "Bir setir"
#define TOK_CLASS_COMMENT_BLOCK_TYPE  1
#define TOK_CLASS_COMMENT_BLOCK_OPENER  "/*"
#define TOK_CLASS_COMMENT_BLOCK_CLOSER  "*/"
#define TOK_CLASS_COMMENT_BLOCK_DEBUG  "Blok"
#endif

#endif // TOKEN_TOKEN_TYPES_COMMENT_H
